apiVersion: batch/v1
kind: CronJob
metadata:
  name: parsejson-job
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: parsejson
            image: python-parsejson:latest
            imagePullPolicy: Never
          restartPolicy: OnFailure